#!/usr/bin/env groovy

podTemplate(yaml: """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: "registry.redhat.io/openshift4/ose-jenkins-agent-maven"
    tty: true
    command: ['cat']
    workdingDir: '/tmp'
  - name: nodejs
    image: "registry.redhat.io/openshift4/jenkins-agent-nodejs-10-rhel7" 
    tty: true
    command: ['cat']
    workingDir: '/tmp'
""") {

     node(POD_LABEL) {
        stage('Get a Maven project') {
            git 'https://github.com/jenkins-docs/simple-java-maven-app.git'
            container('maven') {
                stage('Build a Maven project') {
                    sh """
                        mvn -B clean install
                    """
                }
            }
        }

        stage('Get a Golang project') {
            git url: 'https://github.com/golang/example.git'
            container('golang') {
                stage('Build a Go project') {
                    sh """
                    # Prepare it
                    mkdir -p /go/src/github.com/golang
                    ln -s `pwd` /go/src/github.com/golang/example
                    cd /go/src/github.com/golang/example/hello
                    export GOCACHE=/go/.cache
                    # Build it
                    go build hello.go
                    
                    # Run it
                    ./hello
                    """
                }
            }
        }

    }
}
